### PR TITLE
bump datafusion to 12

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by houqp** [comment]
oh nvm, these are already covered by dependabot update PRs.

**Comment by houqp** [comment]
@returnString do you mind merging those PRs and release a new version?

**Comment by returnString** [comment]
Hey apologies, was on holiday - let me take a look now

**Comment by returnString** [comment]
Just shipped 0.7 with datafusion 12 and sqlparser 24 :)

**Pull request closed without merging**
